version: '3.7'

services:
  landing:
    build: ./landing
    command: npm run dev
    env_file: './landing/.env.local'
    ports:
      - 3000:3000
    volumes:
      - ./landing/:/app
      - /node_modules
      - /.next
